apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: mirrors.tencent.com/alluxio/alluxiotest/venus/pytorch-client:v0.6
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /data
        name: alluxio-cos
  volumes:
  - name: alluxio-cos
    persistentVolumeClaim:
      claimName: alluxio-cos